package com.example.przemyslaw.aw.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CITY".
 */
@Entity
public class City {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private Double latitude;
    private Double longitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public City() {
    }

    public City(Long id) {
        this.id = id;
    }

    @Generated
    public City(Long id, String name, Double latitude, Double longitude) {
        this.id = id;
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
